== Acte 9

=== Scène 1

[.text-center]
**Jack**

Alors, professeur, si je vous comprends bien, innover n’est jamais qu’une affaire de technologies…

[.text-center]
**Prof. Calvet**

Exactement, Jack. Toute avancée technique doit s'accompagner d'une réflexion sur ses conséquences. C’est le rôle de l’Histoire des sciences : nous montrer qu’il ne suffit pas d’inventer. Il faut penser à l’après.

[.text-center]
**Jack**

Et pourtant, une question demeure : qu’est-ce qui nous pousse toujours à avancer ?

[.text-center]
**Prof. Calvet**

La curiosité, Jack. Ce besoin de comprendre et d’aller plus loin. Mais aussi la conviction que chaque question que nous posons – aussi simple soit-elle – peut changer le monde.

"Pourquoi ?" "Comment ?" "Et si ?" Ces petites questions qui mènent à de grandes réponses… ou parfois, à d'autres questions encore plus passionnantes.

Et c’est très bien ainsi. Car le vrai progrès n’est jamais figé. Il continue, génération après génération. Mais ce progrès repose sur une condition essentielle : que nous apprenions de nos erreurs, que nous protégions notre humanité, et que nous soyons les gardiens du monde que nous construisons.

[.text-center]
**Jack**

Alors, une dernière question, professeur : et si… nous étions capables de rêver un futur meilleur, tous ensemble ?

[.text-center]
**Prof. Calvet**

Eh bien, Jack... Je crois que cela dépend d’eux.
